name: testingActions

on: 
  push:
    branches: [main, master]

jobs:
  testing: 
    runs-on: ubuntu-latest

    steps:
    - name: copy repository
      uses: actions/checkout@v4
    
    - name: set_up_python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - run: python short_curl.py
    
